linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - misspell
    - revive
    - gosec
    - prealloc
run:
  skip-files:
    - /zz_generated_
    - _generated
  skip-dirs:
    - generated
  deadline: 5m
  tests: true
  build-tags:
    - test
linters-settings:
  gosec:
    # https://github.com/securego/gosec#available-rules
    config:
      G306: "0644" # Poor file permissions used when writing to a new file
