#!/bin/bash
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
PACKAGE_DIR="${TOP_DIR}/package"

source "${SCRIPTS_DIR}/version"

ARCH=${ARCH:-"amd64"}
SUFFIX="-${ARCH}"

IMAGE=${REPO}/eventrouter:${TAG}
DOCKERFILE=${PACKAGE_DIR}/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

echo "Building image ${IMAGE}"

docker build -f ${DOCKERFILE} -t ${IMAGE} .

echo "Built ${IMAGE}"
