#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/eventrouter:${TAG}
DOCKERFILE=package/Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

buildx build --load -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
